# Generated by Django 5.0.6 on 2024-08-10 20:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=150)),
                ('Montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Utilisateur', models.CharField(max_length=150)),
                ('Reste', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('Description', models.TextField(max_length=700)),
                ('Images', models.ImageField(upload_to='Images/')),
                ('Date_du_début', models.DateField()),
                ('Date_de_fin', models.DateField()),
                ('Interet', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Echéance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('Contribution', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Types_Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default='-', max_length=200)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Types_Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=700)),
                ('Image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utilisateurs', models.CharField(max_length=150)),
                ('Montant', models.DecimalField(decimal_places=1, max_digits=100)),
                ('interet', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Remboursement', models.DecimalField(decimal_places=1, max_digits=100)),
                ('Dates', models.DateField(auto_now=True)),
                ('Projets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CROWDFUNDING.projets')),
                ('Type_Contributions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CROWDFUNDING.types_contributions')),
            ],
        ),
        migrations.AddField(
            model_name='projets',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CROWDFUNDING.types_projets'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Photo', models.ImageField(blank=True, upload_to='Images/')),
                ('is_contri', models.BooleanField(default=True)),
                ('statut', models.CharField(default='CONTRIBUTEUR', max_length=100)),
                ('Dates', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
