# Generated by Django 5.0.6 on 2024-08-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CROWDFUNDING', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='Type_Contributions',
        ),
    ]
