# Generated by Django 5.0.6 on 2024-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CROWDFUNDING', '0002_remove_contributions_type_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='Type_Contributions',
            field=models.CharField(default='rien', max_length=100),
        ),
    ]
