# Generated by Django 5.0.6 on 2024-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CROWDFUNDING', '0003_contributions_type_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='compte',
            field=models.CharField(default='sb-qr7hu32116407@business.example.com', max_length=350),
        ),
        migrations.AddField(
            model_name='user',
            name='compte',
            field=models.CharField(default='sb-qr7hu32116407@business.example.com', max_length=350),
        ),
    ]
